version: "3.9"

services:
  backend:
    image: qiaodeli111/showcase_backend:99fef67
    container_name: backend
    networks:
      - showcase

  frontend:
    image: qiaodeli111/showcase_frontend:99fef67
    container_name: frontend
    networks:
      - showcase
      
  nginx:
    image: qiaodeli111/showcase_nginx:99fef67
    container_name: nginx
    ports:
      - "9080:80"
    networks:
      - showcase

networks:
  showcase: