# Create namespace: dev
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
# Create deployment of backend service
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deploy
  name: backend-deploy
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-deploy
  template:
    metadata:
      labels:
        app: backend-deploy
    spec:
      containers:
      - image: qiaodeli111/showcase_backend:0c4f426
        name: backend
        resources: 
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi

---
# Create service to expose backend deployment
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dev
  labels:
    app: backend-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: backend-deploy
