# .github/workflows/branch-push.yml
name: Branch Push Workflow

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  check_code:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Git for current commit
      id: get_commit_message
      run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
    
    - name: Detect if this is related to K8s manifests update
      id: k8s_manifest_update
      run: |
        if [[ "${{ env.message }}" =~ "Updating K8s manifest files" ]]; then
          echo "IS_K8S_MANIFEST_UPDATE=true" >> $GITHUB_ENV
        else
          echo "IS_K8S_MANIFEST_UPDATE=false" >> $GITHUB_ENV
        fi
    
    outputs:
      IS_K8S_MANIFEST_UPDATE: ${{ env.IS_K8S_MANIFEST_UPDATE }}
  
  build_and_push:
    needs: check_code  # Ensure this job runs after check_code job
    if: needs.check_code.outputs.IS_K8S_MANIFEST_UPDATE == 'false'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend, nginx]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract short SHA
      id: extract_sha
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Build and Push the images
      uses: docker/build-push-action@v2
      with:
        file: ./${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/showcase_${{ matrix.service }}:${{ env.sha_short }}
        context: ./${{ matrix.service }}
    