# .github/workflows/branch-push.yml
name: Branch Push Workflow

on:
  push:
    branches-ignore: ['main'] # 忽略主序列的推送，只触发分支的推送

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend, backend, nginx]
        k8s_deliver: [frontend, backend]
        namespace: [dev]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Git for current commit
      id: get_commit_message
      run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
    
    - name: Detect if this is related to K8s manifests update
      id: k8s_manifest_update
      run: |
        if [[ "${{ steps.get_commit_message.outputs.message }}" =~ "Updating K8s manifest files" ]]; then
          exit 0
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract short SHA
      id: extract_sha
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build and Push the images
      uses: docker/build-push-action@v2
      with:
        file: ./${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/showcase_${{ matrix.service }}:${{ steps.extract_sha.outputs.sha_short }}
        context: ./${{ matrix.service }}
    
    - name: Generate Kubernetes manifest
      run: |
        chmod +x deployment/kubernetes/templates/generate-manifest.sh
        deployment/kubernetes/templates/generate-manifest.sh -n ${{ matrix.namespace }} -a ${{ matrix.k8s_deliver }} -i ${{ secrets.DOCKER_USERNAME }}/showcase_${{ matrix.k8s_deliver }} -t ${{ steps.extract_sha.outputs.sha_short }}

    - name: Generate nginx deployment docker-compose file
      run: |
        chmod +x deployment/kubernetes/templates/generate-manifest.sh
        deployment/kubernetes/templates/generate-manifest.sh -n ${{ matrix.namespace }} -a nginx -i ${{ secrets.DOCKER_USERNAME }}/showcase_nginx -t ${{ steps.extract_sha.outputs.sha_short }}
    
    - name: Commit and push manifest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add deployment/kubernetes/${{ matrix.namespace }}/*.yaml
        git commit -m "Updating K8s manifest files for ${{ matrix.namespace }}"
        git push