# .github/workflows/branch-push.yml
name: Branch Push Workflow

on:
  push:
    branches-ignore: ['master'] # 忽略主序列的推送，只触发分支的推送

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend, backend, nginx]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract short SHA
      id: extract_sha
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build and Push the images
      uses: docker/build-push-action@v2
      with:
        file: ./${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/showcase_${{ matrix.service }}:${{ steps.tag_version.outputs.new_tag }}
        context: ./${{ matrix.service }}
    