# .github/workflows/merge-main.yml
name: Main Branch Merge Workflow

permissions:
  contents: write

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  version_bump:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Bump version
      id: bump_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor
        tag_prefix: ''
    
    outputs:
      NEW_TAG: ${{ steps.bump_version.outputs.new_tag }}

  build_and_push:
    needs: version_bump
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend, nginx]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push the images
      uses: docker/build-push-action@v2
      with:
        file: ./${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/showcase_${{ matrix.service }}:${{ needs.version_bump.outputs.NEW_TAG }}
        context: ./${{ matrix.service }}
    
  update_manifest:
    needs: build_and_push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        namespace: [dev, production]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate Kubernetes manifest for backend
      run: |
        chmod +x deployment/kubernetes/templates/generate-manifest.sh
        deployment/kubernetes/templates/generate-manifest.sh -n ${{ matrix.namespace }} -a backend -i ${{ secrets.DOCKER_USERNAME }}/showcase_backend -t ${{ needs.version_bump.outputs.NEW_TAG }}
    
    - name: Generate Kubernetes manifest for frontend
      run: |
        chmod +x deployment/kubernetes/templates/generate-manifest.sh
        deployment/kubernetes/templates/generate-manifest.sh -n ${{ matrix.namespace }} -a frontend -i ${{ secrets.DOCKER_USERNAME }}/showcase_frontend -t ${{ needs.version_bump.outputs.NEW_TAG }}
    
    - name: Generate nginx deployment docker-compose file
      run: |
        chmod +x deployment/kubernetes/templates/generate-docker-compose.sh
        deployment/kubernetes/templates/generate-docker-compose.sh -n ${{ matrix.namespace }} -a nginx -i ${{ secrets.DOCKER_USERNAME }}/showcase_nginx -t ${{ needs.version_bump.outputs.NEW_TAG }}
    
    - name: Commit and push manifest and tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add deployment/kubernetes/${{ matrix.namespace }}/*.yaml
        git add deployment/local_testing/*
        git commit -m "Updating K8s manifest files for ${{ matrix.namespace }} [skip ci]"
        git tag ${{ needs.version_bump.outputs.NEW_TAG }}
        git push origin main --follow-tags